const publicationData = [
    // ANOS 60
    { title: "The Amazing Spider-Man Vol. 1 (O Espetacular Homem-Aranha Vol. 1)", start: 1963, end: 1998, type: "Principal", code: "asm", description: "A revista mãe de todo o universo Marvel. Aqui Peter Parker evolui de estudante a fotógrafo, enfrenta o luto e estabelece a galeria de vilões mais icônica da cultura pop." },
    { title: "The Spectacular Spider-Man Vol. 1 (O Espetacular Homem-Aranha: Edição Espetacular)", start: 1968, end: 1968, type: "Secundária", code: "ssm", description: "A primeira tentativa de uma revista secundária para o Aranha, lançada em formato de magazine em preto e branco. Durou apenas duas edições." },

    // ANOS 70
    { title: "Marvel Team-Up (Marvel Team-Up)", start: 1972, end: 1985, type: "Secundária", code: "ssm", description: "Série onde o Homem-Aranha (e ocasionalmente outros) faziam parcerias mensais com diferentes heróis do universo Marvel." },
    { title: "Spidey Super Stories (Super Histórias do Aranha)", start: 1974, end: 1982, type: "Infantil", code: "spin", description: "Histórias criadas para o público mais jovem, baseadas nas esquetes live-action do programa The Electric Company." },
    { title: "Peter Parker, The Spectacular Spider-Man (Peter Parker, O Espetacular Homem-Aranha)", start: 1976, end: 1998, type: "Secundária", code: "ssm", description: "Enquanto a série principal focava em grandes batalhas, Spectacular dedicava-se ao lado humano e universitário de Peter, com histórias urbanas e foco em vilões como o Rei do Crime." },

    // ANOS 80
    { title: "Web of Spider-Man Vol. 1 (A Teia do Homem-Aranha Vol. 1)", start: 1985, end: 1995, type: "Secundária", code: "wos", description: "O terceiro título mensal regular, criado para dar vazão à imensa popularidade do herói. Foi o palco de momentos sombrios como o início da 'Última Caçada de Kraven'." },
    { title: "Kraven's Last Hunt (A Última Caçada de Kraven)", start: 1987, end: 1987, type: "Evento", code: "evnt", description: "O épico sombrio onde Kraven, o Caçador, enterra Peter Parker vivo e assume sua identidade para provar que é superior." },

    // ANOS 90
    { title: "Spider-Man Vol. 1 (Homem-Aranha Vol. 1 - McFarlane)", start: 1990, end: 1998, type: "Principal", code: "asm", description: "A revista que quebrou recordes de vendas. McFarlane trouxe uma arte detalhada e sombria, focada em terror e ação visual exagerada que definiu a estética dos anos 90." },
    { title: "Spider-Man 2099 Vol. 1 (Homem-Aranha 2099 Vol. 1)", start: 1992, end: 1996, type: "Alternativo", code: "ult", description: "Esqueça o Peter Parker; aqui conhecemos Miguel O'Hara num futuro cyberpunk controlado por corporações malignas. Um clássico cult independente." },
    { title: "Spider-Man Unlimited Vol. 1 (Homem-Aranha Sem Limites Vol. 1)", start: 1993, end: 1998, type: "Antologia", code: "wos", description: "Série trimestral com edições maiores que permitiam histórias mais densas e experimentais, explorando cantos pouco vistos da vida de Peter." },
    { title: "Maximum Carnage (Carnificina Total)", start: 1993, end: 1993, type: "Evento", code: "evnt", description: "Um crossover massivo onde o Aranha e o Venom precisam se aliar para parar a matança desenfreada do Carnificina por Nova York." },
    { title: "The Clone Saga (A Saga do Clone)", start: 1994, end: 1996, type: "Evento", code: "evnt", description: "A fase mais controversa e épica que explora a crise de identidade de Peter ao descobrir Ben Reilly, o seu clone perfeito que assume o manto do Aranha." },
    { title: "Spider-Man Adventures (Aventuras do Homem-Aranha)", start: 1994, end: 1996, type: "Adaptação", code: "spin", description: "Histórias em quadrinhos adaptando o imensamente popular desenho animado dos anos 90." },
    { title: "Untold Tales of Spider-Man (Contos Inéditos do Homem-Aranha)", start: 1995, end: 1997, type: "Flashback", code: "wos", description: "Uma carta de amor à Era de Prata. Histórias inéditas situadas cronologicamente entre as edições originais dos anos 60 de Stan Lee." },
    { title: "Sensational Spider-Man Vol. 1 (O Sensacional Homem-Aranha Vol. 1)", start: 1996, end: 1998, type: "Secundária", code: "wos", description: "Substituiu Web of Spider-Man. Foi a revista principal de Ben Reilly quando ele assumiu o manto, marcando uma fase nova e mais leve." },
    { title: "Spider-Girl Vol. 1 (Garota-Aranha Vol. 1)", start: 1998, end: 2006, type: "Alternativo", code: "ult", description: "No universo MC2, acompanhamos Mayday Parker, a filha de Peter e Mary Jane que herda os poderes do pai. A heroína da Marvel com a revista mais duradoura." },
    { title: "The Amazing Spider-Man Vol. 2 (O Espetacular Homem-Aranha Vol. 2)", start: 1999, end: 2003, type: "Principal", code: "asm", description: "O relançamento do herói para um novo milênio após a fase dos clones, focando no recomeço da vida de Peter Parker." },
    { title: "Peter Parker: Spider-Man Vol. 2 (Peter Parker: Homem-Aranha Vol. 2)", start: 1999, end: 2003, type: "Secundária", code: "ssm", description: "Continuação da revista Spider-Man focando na vida pessoal de Peter e histórias complementares à série principal." },
    { title: "Webspinners: Tales of Spider-Man (Tece-Teias: Contos do Homem-Aranha)", start: 1999, end: 2000, type: "Antologia", code: "wos", description: "Série de antologia explorando contos fechados que não se prendiam à cronologia atual, abrangendo várias eras do personagem." },

    // ANOS 2000
    { title: "Ultimate Spider-Man (Ultimate Homem-Aranha)", start: 2000, end: 2011, type: "Alternativo", code: "ult", description: "O melhor ponto de entrada para novos leitores. Reconstrói a origem do Peter do zero, sem o peso de 40 anos de continuidade, para o século XXI." },
    { title: "Spider-Man's Tangled Web (A Teia Emaranhada do Homem-Aranha)", start: 2001, end: 2003, type: "Antologia", code: "wos", description: "Focou em personagens periféricos e nos vilões do universo do Aranha, com uma pegada mais independente e experimental." },
    { title: "Spider-Man: Blue (Homem-Aranha: Azul)", start: 2002, end: 2003, type: "Minissérie", code: "mini", description: "Uma obra de arte melancólica. Peter grava fitas para a falecida Gwen Stacy, relembrando como se apaixonaram. Focada em sentimentos, não em porrada." },
    { title: "The Amazing Spider-Man Vol. 1 - JMS Era (O Espetacular Homem-Aranha Vol. 1 - Fase JMS)", start: 2003, end: 2012, type: "Principal", code: "asm", description: "A era Straczynski. Introduz o conceito de Totens Aranha, a volta de Mary Jane e Peter como professor de liceu. Essencial para o cânone moderno." },
    { title: "The Spectacular Spider-Man Vol. 2 (O Espetacular Homem-Aranha: Edição Espetacular Vol. 2)", start: 2003, end: 2005, type: "Secundária", code: "ssm", description: "Relançamento da clássica série secundária, acompanhando histórias mais contidas de Peter Parker no início dos anos 2000." },
    { title: "Marvel Knights Spider-Man (Homem-Aranha: Cavaleiros Marvel)", start: 2004, end: 2006, type: "Maduro", code: "ssm", description: "Oferece uma visão mais cinematográfica e violenta do herói, com sagas de 12 edições que parecem blockbusters de cinema." },
    { title: "Spider-Man Unlimited Vol. 3 (Homem-Aranha Sem Limites Vol. 3)", start: 2004, end: 2006, type: "Antologia", code: "wos", description: "Série bimestral que destacava o herói em histórias curtas por novos e promissores talentos da indústria." },
    { title: "Spider-Man: House of M (Homem-Aranha: Dinastia M)", start: 2005, end: 2005, type: "Minissérie", code: "mini", description: "Minissérie ligada ao evento Dinastia M, mostrando o mundo onde Gwen está viva e Peter tem a vida que sempre sonhou." },
    { title: "The Other (O Outro)", start: 2005, end: 2006, type: "Evento", code: "evnt", description: "Saga que cruza vários títulos. Peter enfrenta uma doença mortal e passa por uma mutação física que redefine a natureza dos seus poderes." },
    { title: "Friendly Neighborhood Spider-Man Vol. 1 (O Amigão da Vizinhança Homem-Aranha Vol. 1)", start: 2005, end: 2007, type: "Secundária", code: "ssm", description: "Uma revista mais leve e descontraída, focada nas interações de Peter Parker com a comunidade." },
    { title: "The Sensational Spider-Man Vol. 2 (O Sensacional Homem-Aranha Vol. 2)", start: 2006, end: 2007, type: "Secundária", code: "wos", description: "Continuou a linha Marvel Knights, aprofundando os relacionamentos e a tensão após os eventos da Guerra Civil." },
    { title: "Spider-Man Loves Mary Jane (O Homem-Aranha Ama Mary Jane)", start: 2006, end: 2007, type: "Spin-Off", code: "spin", description: "Uma charmosa série focada no drama adolescente e nos romances de Mary Jane Watson durante a juventude com Peter." },
    { title: "Civil War (Guerra Civil)", start: 2006, end: 2007, type: "Evento", code: "evnt", description: "Peter revela sua identidade secreta ao mundo, mudando para sempre a sua vida e dividindo os heróis da Marvel." },
    { title: "One More Day (Um Dia a Mais)", start: 2007, end: 2007, type: "Evento", code: "evnt", description: "A saga mais polêmica onde Peter faz um pacto com Mephisto para salvar sua Tia May, sacrificando seu casamento com Mary Jane." },
    { title: "Spider-Man Noir (Homem-Aranha Noir)", start: 2009, end: 2010, type: "Alternativo", code: "ult", description: "E se o Aranha fosse um detetive dos anos 30 durante a Grande Depressão? Uma estética de filmes clássicos com muita sombra e violência." },

    // ANOS 2010
    { title: "Avenging Spider-Man (O Vingador Homem-Aranha)", start: 2011, end: 2013, type: "Secundária", code: "ssm", description: "Uma série de ação rápida focada nas aventuras do Homem-Aranha atuando junto com os Vingadores." },
    { title: "Ultimate Comics: Spider-Man (Ultimate Comics: Homem-Aranha)", start: 2011, end: 2014, type: "Alternativo", code: "ult", description: "A estreia de Miles Morales! Após a morte do Peter Parker do Universo Ultimate, o jovem Miles assume o manto." },
    { title: "Spider-Men (Homens-Aranha)", start: 2012, end: 2012, type: "Minissérie", code: "mini", description: "O histórico encontro entre o Peter Parker do universo original e o Miles Morales do universo Ultimate." },
    { title: "The Superior Spider-Man Vol. 1 (O Superior Homem-Aranha Vol. 1)", start: 2013, end: 2014, type: "Principal", code: "asm", description: "Otto Octavius rouba o corpo de Peter. É a história de um vilão a tentar (e falhar) ser um herói melhor que o original." },
    { title: "The Superior Foes of Spider-Man (Os Inimigos Superiores do Homem-Aranha)", start: 2013, end: 2014, type: "Spin-Off", code: "spin", description: "Uma comédia brilhante focada no Sexteto Sinistro do Bumerangue e as suas trapalhadas para conseguir dar o grande golpe." },
    { title: "The Amazing Spider-Man Vol. 3 (O Espetacular Homem-Aranha Vol. 3)", start: 2014, end: 2015, type: "Principal", code: "asm", description: "O retorno de Peter Parker após o controle do Doutor Octopus, preparando o terreno para grandes eventos multiversais." },
    { title: "Spider-Verse (Aranhaverso)", start: 2014, end: 2015, type: "Evento", code: "evnt", description: "O evento épico que uniu todos os Homens-Aranha de todas as realidades contra vampiros energéticos. Deu origem aos filmes animados." },
    { title: "Spider-Man 2099 Vol. 2 (Homem-Aranha 2099 Vol. 2)", start: 2014, end: 2015, type: "Secundária", code: "ssm", description: "Miguel O'Hara está preso no presente e precisa garantir que o futuro da Alchemax não destrua a linha do tempo." },
    { title: "Spider-Gwen Vol. 1 (Gwen-Aranha Vol. 1)", start: 2015, end: 2023, type: "Alternativo", code: "ult", description: "Gwen Stacy é a mordida pela aranha, enquanto Peter Parker se torna o Lagarto. Uma das personagens mais amadas da última década." },
    { title: "The Amazing Spider-Man Vol. 4 (O Espetacular Homem-Aranha Vol. 4)", start: 2015, end: 2017, type: "Principal", code: "asm", description: "Peter Parker vira um CEO global ao estilo Tony Stark, levando a Parker Industries pelo mundo com um novo traje high-tech." },
    { title: "Spider-Man Vol. 2 (Homem-Aranha Vol. 2)", start: 2016, end: 2018, type: "Principal", code: "asm", description: "A série focada em Miles Morales após ele integrar permanentemente o universo principal da Marvel (Terra-616)." },
    { title: "Spider-Man/Deadpool (Homem-Aranha/Deadpool)", start: 2016, end: 2019, type: "Crossover", code: "ssm", description: "A 'bromance' mais improvável da Marvel. Muita comédia, quebra da quarta parede e Deadpool a tentar convencer o Aranha a ser seu melhor amigo." },
    { title: "The Amazing Spider-Man: Renew Your Vows (O Espetacular Homem-Aranha: Renovando Seus Votos)", start: 2016, end: 2018, type: "Alternativo", code: "ult", description: "Um presente para os fãs antigos: uma realidade onde Peter e Mary Jane nunca se separaram e agora criam a sua filha super-heroína." },
    { title: "Peter Parker, The Spectacular Spider-Man Vol. 2 (Peter Parker, O Espetacular Homem-Aranha Vol. 2)", start: 2017, end: 2018, type: "Secundária", code: "ssm", description: "Um retorno ao lado urbano e amigão da vizinhança de Peter após as aventuras globais como CEO." },
    { title: "The Amazing Spider-Man Vol. 5 (O Espetacular Homem-Aranha Vol. 5)", start: 2018, end: 2022, type: "Principal", code: "asm", description: "A fase de Nick Spencer que retornou Peter às suas raízes, reatou o namoro com Mary Jane e focou num terror sutil com o vilão Condenado." },
    { title: "Spider-Geddon (Aranha-Gedon)", start: 2018, end: 2018, type: "Evento", code: "evnt", description: "A sequência direta do Aranhaverso, com o retorno dos Herdeiros, forçando as Aranhas do multiverso a se unirem novamente." },
    { title: "Miles Morales: Spider-Man Vol. 1 (Miles Morales: Homem-Aranha Vol. 1)", start: 2018, end: 2022, type: "Principal", code: "asm", description: "Miles Morales continua a se estabelecer como o Homem-Aranha definitivo do Brooklyn em sua nova revista solo." },
    { title: "Friendly Neighborhood Spider-Man Vol. 2 (O Amigão da Vizinhança Homem-Aranha Vol. 2)", start: 2019, end: 2019, type: "Secundária", code: "ssm", description: "Uma revista tocante e íntima que equilibrou pequenas ações comunitárias de Peter e dramas familiares." },
    { title: "Spider-Man: Life Story (Homem-Aranha: História de Vida)", start: 2019, end: 2019, type: "Minissérie", code: "mini", description: "Considerada por muitos a melhor história recente. Peter envelhece em tempo real desde 1962, enfrentando guerras e crises reais década a década." },
    { title: "Absolute Carnage (Carnificina Absoluta)", start: 2019, end: 2019, type: "Evento", code: "evnt", description: "Cletus Kasady ressurge ligado ao deus simbionte Knull, colocando Aranha, Venom e o universo Marvel em alerta máximo." },

    // ANOS 2020
    { title: "Spider-Man: Spider's Shadow (Homem-Aranha: A Sombra da Aranha)", start: 2021, end: 2021, type: "Alternativo", code: "ult", description: "Um 'O Que Aconteceria Se' focado no terror. Peter torna-se um assassino implacável após sucumbir ao controlo total do simbionte Venom." },
    { title: "The Amazing Spider-Man Vol. 6 (O Espetacular Homem-Aranha Vol. 6)", start: 2022, end: 2025, type: "Principal", code: "asm", description: "A fase atual e polémica de Zeb Wells. Peter está isolado, cometeu um erro terrível e a sua vida está em pedaços. Essencial para acompanhar o que sai agora." },
    { title: "Miles Morales: Spider-Man Vol. 2 (Miles Morales: Homem-Aranha Vol. 2)", start: 2022, end: 2025, type: "Principal", code: "asm", description: "O relançamento contínuo das aventuras de Miles com novos vilões e desafios para equilibrar sua juventude e heroísmo." },
    { title: "Spider-Punk (Punk-Aranha)", start: 2022, end: 2022, type: "Minissérie", code: "mini", description: "Anarquia total. Hobie Brown luta contra o sistema numa realidade onde o fascismo domina e a música é a sua maior arma." },
    { title: "Dark Web (Teia Sombria)", start: 2022, end: 2023, type: "Evento", code: "evnt", description: "A clone de Jean Grey (Madelyne Pryor) e o clone de Peter (Chasm/Ben Reilly) unem forças contra Nova York num evento caótico." },
    { title: "The Superior Spider-Man Vol. 3 (O Superior Homem-Aranha Vol. 3)", start: 2024, end: 2024, type: "Minissérie", code: "mini", description: "Um retorno para comemorar os dez anos do Superior Homem-Aranha original, explorando novas facetas de Otto Octavius." },
    { title: "Ultimate Spider-Man (Ultimate Homem-Aranha 2024)", start: 2024, end: 2025, type: "Alternativo", code: "ult", description: "O novo sucesso massivo de Hickman. Um Peter Parker adulto, já casado e com filhos, ganha os poderes tardiamente num mundo onde os heróis não existiam." },
    { title: "Spider-Boy (Garoto-Aranha)", start: 2024, end: 2025, type: "Spin-Off", code: "spin", description: "O jovem ajudante esquecido do Aranhaverso que agora busca encontrar seu lugar no universo principal enfrentando bizarros vilões." },
    { title: "The Amazing Spider-Man Vol. 7 (O Espetacular Homem-Aranha Vol. 7)", start: 2025, end: 2025, type: "Principal", code: "asm", description: "Nova fase a ser lançada liderada pela reinvenção das aventuras de Peter Parker para a década de 2020." }
];